import type { Problem } from "./types";

function atHours(daysAgo: number, hour: number) {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, 12 + (daysAgo % 17), 0, 0);
  return d.toISOString();
}

export function createSeed(): Problem[] {
  return [
    {
      id: "seed-two-sum",
      title: "Two Sum",
      platform: "LeetCode",
      url: "https://leetcode.com/problems/two-sum/",
      language: "javascript",
      difficulty: "easy",
      status: "solved",
      topics: ["arrays", "hashing"],
      notes: "Hash map of complements. O(n) after the naive nested loop.",
      timeSpentMin: 28,
      createdAt: atHours(18, 20),
      updatedAt: atHours(18, 21),
      solvedAt: atHours(18, 21),
    },
    {
      id: "seed-valid-parens",
      title: "Valid Parentheses",
      platform: "LeetCode",
      url: "https://leetcode.com/problems/valid-parentheses/",
      language: "javascript",
      difficulty: "easy",
      status: "solved",
      topics: ["stack", "strings"],
      notes: "Stack of expected closers. Watch the empty-stack pop.",
      timeSpentMin: 22,
      createdAt: atHours(16, 19),
      updatedAt: atHours(16, 19),
      solvedAt: atHours(16, 19),
    },
    {
      id: "seed-flexbox",
      title: "Holy Grail layout in Flexbox",
      platform: "Frontend Mentor",
      url: "",
      language: "html-css",
      difficulty: "easy",
      status: "solved",
      topics: ["flexbox", "layout"],
      notes: "Header / nav / main / aside / footer without grid. Sticky footer via margin-top auto.",
      timeSpentMin: 45,
      createdAt: atHours(14, 16),
      updatedAt: atHours(14, 17),
      solvedAt: atHours(14, 17),
    },
    {
      id: "seed-sql-joins",
      title: "Orders with customers — inner vs left join",
      platform: "HackerRank",
      url: "",
      language: "sql",
      difficulty: "medium",
      status: "solved",
      topics: ["joins", "aggregation"],
      notes: "LEFT JOIN keeps customers with no orders. GROUP BY after the join, not before.",
      timeSpentMin: 40,
      createdAt: atHours(12, 21),
      updatedAt: atHours(12, 22),
      solvedAt: atHours(12, 22),
    },
    {
      id: "seed-binary-search",
      title: "Binary Search",
      platform: "LeetCode",
      url: "https://leetcode.com/problems/binary-search/",
      language: "python",
      difficulty: "easy",
      status: "solved",
      topics: ["binary-search", "arrays"],
      notes: "Inclusive lo, exclusive hi. Mid overflow: lo + (hi-lo)//2.",
      timeSpentMin: 18,
      createdAt: atHours(11, 10),
      updatedAt: atHours(11, 10),
      solvedAt: atHours(11, 10),
    },
    {
      id: "seed-grid-gallery",
      title: "Responsive image gallery",
      platform: "Frontend Mentor",
      url: "",
      language: "html-css",
      difficulty: "easy",
      status: "solved",
      topics: ["grid", "media-queries"],
      notes: "auto-fit minmax(220px, 1fr). Aspect-ratio on the cards, object-fit cover.",
      timeSpentMin: 50,
      createdAt: atHours(9, 18),
      updatedAt: atHours(9, 19),
      solvedAt: atHours(9, 19),
    },
    {
      id: "seed-merge-intervals",
      title: "Merge Intervals",
      platform: "LeetCode",
      url: "https://leetcode.com/problems/merge-intervals/",
      language: "typescript",
      difficulty: "medium",
      status: "solved",
      topics: ["intervals", "sorting"],
      notes: "Sort by start, then fold if current.start <= last.end.",
      timeSpentMin: 55,
      createdAt: atHours(7, 21),
      updatedAt: atHours(7, 22),
      solvedAt: atHours(7, 22),
    },
    {
      id: "seed-express-crud",
      title: "Express REST notes API",
      platform: "Project",
      url: "",
      language: "javascript",
      difficulty: "medium",
      status: "solved",
      topics: ["rest", "express", "validation"],
      notes: "CRUD with express.json, 404 on missing id, Joi on the body.",
      timeSpentMin: 95,
      createdAt: atHours(6, 15),
      updatedAt: atHours(6, 17),
      solvedAt: atHours(6, 17),
    },
    {
      id: "seed-longest-substr",
      title: "Longest Substring Without Repeating Characters",
      platform: "LeetCode",
      url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
      language: "javascript",
      difficulty: "medium",
      status: "revisited",
      topics: ["sliding-window", "hashing"],
      notes: "Need to skip ahead when the last index of a char is inside the window.",
      timeSpentMin: 70,
      createdAt: atHours(5, 20),
      updatedAt: atHours(2, 21),
      solvedAt: atHours(5, 21),
    },
    {
      id: "seed-react-board",
      title: "Kanban board with drag state",
      platform: "Project",
      url: "",
      language: "typescript",
      difficulty: "medium",
      status: "in-progress",
      topics: ["react", "state", "dnd"],
      notes: "Columns as arrays. Optimistic move, then persist. Still wiring the drop target.",
      timeSpentMin: 80,
      createdAt: atHours(4, 19),
      updatedAt: atHours(1, 20),
    },
    {
      id: "seed-auth-flow",
      title: "JWT login flow on the client",
      platform: "Project",
      url: "",
      language: "javascript",
      difficulty: "medium",
      status: "in-progress",
      topics: ["auth", "fetch", "storage"],
      notes: "Access token in memory, refresh in httpOnly discussion. Interceptor retries 401 once.",
      timeSpentMin: 60,
      createdAt: atHours(3, 17),
      updatedAt: atHours(0, 18),
    },
    {
      id: "seed-cycle",
      title: "Detect cycle in a directed graph",
      platform: "GeeksforGeeks",
      url: "",
      language: "java",
      difficulty: "hard",
      status: "in-progress",
      topics: ["graphs", "dfs"],
      notes: "Color states: white / grey / black. Grey back-edge means a cycle.",
      timeSpentMin: 42,
      createdAt: atHours(2, 22),
      updatedAt: atHours(1, 22),
    },
    {
      id: "seed-lru",
      title: "LRU Cache",
      platform: "LeetCode",
      url: "https://leetcode.com/problems/lru-cache/",
      language: "typescript",
      difficulty: "hard",
      status: "todo",
      topics: ["design", "linked-list", "hashing"],
      notes: "Map plus doubly linked list. Draw the pointers before coding.",
      timeSpentMin: 0,
      createdAt: atHours(2, 9),
      updatedAt: atHours(2, 9),
    },
    {
      id: "seed-dijkstra",
      title: "Network delay time (Dijkstra)",
      platform: "LeetCode",
      url: "https://leetcode.com/problems/network-delay-time/",
      language: "python",
      difficulty: "hard",
      status: "todo",
      topics: ["graphs", "heap"],
      notes: "Min-heap of (dist, node). Early continue if a worse dist is popped.",
      timeSpentMin: 0,
      createdAt: atHours(1, 11),
      updatedAt: atHours(1, 11),
    },
    {
      id: "seed-palindrome",
      title: "Palindrome Number",
      platform: "LeetCode",
      url: "https://leetcode.com/problems/palindrome-number/",
      language: "python",
      difficulty: "easy",
      status: "solved",
      topics: ["math", "two-pointers"],
      notes: "Reverse half the digits. Negative numbers are out.",
      timeSpentMin: 16,
      createdAt: atHours(0, 10),
      updatedAt: atHours(0, 10),
      solvedAt: atHours(0, 10),
    },
  ];
}
